# Experimental Docker compose override file the database PostgreSQL.

services:

  # the database server
  db:
    image: ${OTOBO_IMAGE_DB:-postgres:18-trixie}
    user: postgres:postgres
    cap_drop:
      - ALL
    cap_add:
      - CAP_SYS_CHROOT
    restart: always
    logging:
      driver: "local"
      options:
        max-file: "5"
        max-size: "10m"
    volumes:
      - postgresql_data:/var/lib/postgresql

    # Within the container network the PostgreSQL server listens to its default port 5432.
    # Per default this port is not exposed to the outside world.
    # For development it can be useful to expose the port 5432.
    # Uncomment the following lines for making PostgreSQL available.
    # ports:
    #   - "5432:5432"

    # Set the db root password which has to be entered when running otobo/installer.pl.
    # The passwort is secret and can be stored in the file .env.
    # The content of the .env file is something like:
    # OTOBO_DB_ROOT_PASSWORD=otobo_root
    environment:
      POSTGRES_PASSWORD: ${OTOBO_DB_ROOT_PASSWORD:?err}

    # For PostgreSQL no options have to be provided.
    # Note that for 'command' the complete list of options is replaced.
    command: []

    # The health check for PostgreSQL is still to be determined.
    healthcheck:
      test: 'true'

volumes:
  postgresql_data: {}
